### ISSUE TITLE
Package outdated

### ISSUE THREAD

**Issue by ColinDuquesnoy** [KaOS-Community-Packages/telegram-desktop#1]
Please consider updating this package. FYI, the latest version (0.8.51) added support for system tray integration.

If you don't have the time to update this package, I'll try to submit a PR.

**Comment by demmm** [comment]
No need for a PR, there are no set maintainers in KCP, anyone with a User account can edit all files directly.

**Comment by ColinDuquesnoy** [comment]
@demmm  Thank you, looks like I did not understand that when I read the KCP guide. I'll apply for a kcp account and make the changes myself.
